/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as GamesTicTacToeRouteImport } from './routes/games.tic-tac-toe'
import { Route as GamesSnakeRouteImport } from './routes/games.snake'
import { Route as GamesAppleRouteImport } from './routes/games.apple'

const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTicTacToeRoute = GamesTicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSnakeRoute = GamesSnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => GamesRoute,
} as any)
const GamesAppleRoute = GamesAppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/apple': typeof GamesAppleRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/apple': typeof GamesAppleRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/apple': typeof GamesAppleRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/games/apple'
    | '/games/snake'
    | '/games/tic-tac-toe'
    | '/watch/$videoId'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/apple'
    | '/games/snake'
    | '/games/tic-tac-toe'
    | '/watch/$videoId'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/games/apple'
    | '/games/snake'
    | '/games/tic-tac-toe'
    | '/watch/$videoId'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRouteWithChildren
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tic-tac-toe': {
      id: '/games/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/games/tic-tac-toe'
      preLoaderRoute: typeof GamesTicTacToeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/snake': {
      id: '/games/snake'
      path: '/snake'
      fullPath: '/games/snake'
      preLoaderRoute: typeof GamesSnakeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/apple': {
      id: '/games/apple'
      path: '/apple'
      fullPath: '/games/apple'
      preLoaderRoute: typeof GamesAppleRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesAppleRoute: typeof GamesAppleRoute
  GamesSnakeRoute: typeof GamesSnakeRoute
  GamesTicTacToeRoute: typeof GamesTicTacToeRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesAppleRoute: GamesAppleRoute,
  GamesSnakeRoute: GamesSnakeRoute,
  GamesTicTacToeRoute: GamesTicTacToeRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRouteWithChildren,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
