/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/watch/$videoId'
  id: '__root__' | '/' | '/watch/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
